import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const locales = ['en', 'id'];
const defaultLocale = 'en';

function getFallbackLocale(request: NextRequest): string {
  // 1. Try reading the synchronized locale cookie
  const cookieLocale = request.cookies.get('NEXT_LOCALE')?.value;
  if (cookieLocale && locales.includes(cookieLocale)) return cookieLocale;

  // 2. Fallback to parsing the browser's Accept-Language header
  const acceptLanguage = request.headers.get('accept-language');
  if (acceptLanguage) {
    const preferredLocale = acceptLanguage
      .split(',')
      .map(lang => lang.split(';')[0].trim().toLowerCase())
      .find(lang => locales.includes(lang) || locales.includes(lang.split('-')[0]));
      
    if (preferredLocale) {
      return locales.includes(preferredLocale) ? preferredLocale : preferredLocale.split('-')[0];
    }
  }

  return defaultLocale;
}

export function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  const pathnameHasLocale = locales.some(
    (locale) => pathname.startsWith(`/${locale}/`) || pathname === `/${locale}`
  );

  if (pathnameHasLocale) return NextResponse.next();

  const locale = getFallbackLocale(request);
  request.nextUrl.pathname = `/${locale}${pathname}`;
  return NextResponse.redirect(request.nextUrl);
}

export const config = {
  /*
   * Match all request paths except for the ones starting with:
   * - api (API routes)
   * - _next/static (static files)
   * - _next/image (image optimization files)
   * - images (your public/images folder)
   * - favicon.ico, site.webmanifest, etc.
   * - Static image extensions (webp, svg, png, jpg, jpeg, gif, ico)
   * - sitemap.xml autogenerated file
   */
  matcher: [
    '/((?!api|_next/static|_next/image|images|favicon.ico|sitemap.xml|.*\\.webp|.*\\.svg|.*\\.png|.*\\.jpg|.*\\.jpeg|.*\\.gif|.*\\.ico).*)'
  ],
};