import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/NavigationBar";
import NextTopLoader from "nextjs-toploader";
import Footer from "@/components/layout/Footer";
import { Locale } from "@/lib/get-dictionary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>; // 1. Must be typed as string to pass Next.js validation
}>) {
  // 2. Safely assert your explicit Locale type here after resolution
  const resolvedParams = await params;
  const lng = resolvedParams.lng as Locale;

  return (
    <html
      data-scroll-behavior="smooth"
      lang={lng} // 3. Updated this from "en" to dynamically reflect the current locale
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-void text-white">
        <NextTopLoader 
          color="#22d3ee" 
          shadow="0 0 10px rgba(34, 211, 238, 0.12)" 
          showForHashAnchor={false} 
        />
        <Navbar lng={lng} />
        {children}
        <Footer lng={lng} />
      </body>
    </html>
  );
}